# Generated by Django 4.2.7 on 2025-05-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_birth_country_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('mpv', 'MPV'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup Truck'), ('van', 'Van'), ('minivan', 'Minivan')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Müsait'), ('rented', 'Kiralandı'), ('maintenance', 'Bakımda'), ('unavailable', 'Kullanım Dışı')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('seat_count', models.IntegerField(default=5)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Benzin'), ('diesel', 'Dizel'), ('hybrid', 'Hibrit'), ('electric', 'Elektrik'), ('lpg', 'LPG')], max_length=50)),
                ('transmission', models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Otomatik'), ('semi_automatic', 'Yarı Otomatik')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Erkek'), ('female', 'Kadın')], max_length=10),
        ),
    ]
