# Generated by Django 4.2.7 on 2025-05-22 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(default='DEFAULTPLATE', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seat_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Müsait'), ('rented', 'Kiralandı'), ('maintenance', 'Bakımda'), ('unavailable', 'Kullanım Dışı')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('mpv', 'MPV'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup Truck'), ('van', 'Van'), ('minivan', 'Minivan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Benzin'), ('diesel', 'Dizel'), ('hybrid', 'Hibrit'), ('electric', 'Elektrik'), ('lpg', 'LPG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Otomatik'), ('semi_automatic', 'Yarı Otomatik')], max_length=20),
        ),
    ]
